### ISSUE TITLE
colorpicker repository URL is not working

### ISSUE THREAD

**Issue by ygerasimov** [ymcatwincities/openy-project#1]
See https://github.com/ymcatwincities/openy-project/blob/8.1.x/composer.json#L78

There is no such repo https://github.com/jaypan/jquery_colorpicker_composer.

Probably we should use https://github.com/jaypan/jquery_colorpicker instead.

**Comment by alexschedrov** [comment]
Thank you for that catch!

The reason why installation process got broken, because https://github.com/jaypan/jquery_colorpicker_composer has been removed for some reason and moved to https://github.com/jaypan/jquery_colorpicker 3 days ago. It should be fixed now in openy-project and in installation profile.

![image](https://cloud.githubusercontent.com/assets/1316234/22928091/4473a938-f2bd-11e6-8210-94790b743af2.png)
